### ISSUE TITLE
Support for arrays and matrices

### ISSUE THREAD

**Issue by johnblommers** [Enchufa2/errors#4]
Consider the following code with which we attempt to define array x to contain 5 copies of x1, a variable of class errors:

```
> library(errors)
> x1 = 7
> errors(x1) = 1
> x1
7 +/- 1                    # x1 is of class errors
> x = array(x1, 5)  # try to create an array all elements set to x1
> x
[1] 7 7 7 7 7       # x is not of class errors but should be
> x = rep(x1, 5)  # work-around
> x
errors: 1 1 1 1 1
[1] 7 7 7 7 7
> 
```

There is every chance that I am reading too much into the array function. What do you think?

**Comment by Enchufa2** [comment]
Arrays and matrices are not well supported yet. Many R methods are quite aggressive with custom classes and attributes, in particular, those for dealing with arrays and matrices, so this is not trivial. However, it would be a nice addition for a future release, so I'll keep this open until I have time to look deeper into this.

**Comment by edzer** [comment]
Might be easier than you think: matrix and array don't use the class attribute, but follow from a `dim` attribute. See for instance https://github.com/edzer/units/commit/7c097cbf49016f4dde7d2be781567e7a666bccd5 ; you can always get & set that, in case it is NULL, you have a vector.

**Comment by Enchufa2** [comment]
That's interesting. I'll take a look, thanks!

**Comment by Enchufa2** [comment]
@johnblommers: I'm taking a look at this. Note that neither `array` or `matrix` could result in an array/matrix with errors, because these two methods are not generic, and the input data is coerced to a vector by design. 

However, `as.array` works out of the box, and `as.matrix` requires an implementation for `errors` objects that of course will be provided in this package.
